version: '3.6'

services:
  backend:
    build:
      context: .
    container_name: app_backend
    environment:
      - FLASK_APP=app/app.py
      - FLASK_ENV=development
      - MONGO_URI=
    ports:
      - 5000:5000